export const pageLevelLocalization = {
  header: {
    home: "صفحه اصلی",
    fantasy: "فانتزی",
    history: "ادبیات کلاسیک",
    juniuor: "کودک و نوجوان",
    litriture: "ادبی",
    novel: "رمان",
    contact: "ارتباط با ما",
    about: "درباره ما",
  },
  footer: {
    address: "تهران - ستاری - بلوار لاله - پاساژ سمرقند طبقه 3 فروشگاه بوکتین",
    number: "021-4443258",
    text: "...بیشتر",
  },
  loginPage: {
    welcome: "به بوکتین خوش آمدید!",
    login: "به اکانت خود وارد شوید",
    passwordLabel: "رمزعبور :",
    emailLabel: "ایمیل :",
    alredyHaveAnAccount: "قبلا ثبت نام نکردید؟",
    sinUp: "ثبت نام کنید",
    errorRequiredEmailInput: "ایمیل را وارد کنید",
    errorRequiredPaaswordInput: "رمز عبور را وارد کنید",
    errorEmailInput: "ایمیل وارد شده نامعتبر است ",
    errorPasswordInput: "رمزعبور وارد شده نامعتبر است ",
    loginBtn: "ورود",
    emailError: "ایمیل خودرا وارد کنید",
    passwordError: "رمز عبور خودرا وارد کنید",
  },
  singUpPageLoc: {
    welcome: "به آبتیکا خوش آمدید!",
    singUp: "اکانت خود را بسازید",
    passwordLabel: "رمزعبور :",
    passwordLabel2: "تکرار رمز عبور",
    emailLabel: "ایمیل :",
    alredyHaveAnAccount: "قبلا ثبت نام کردید؟",
    login: "وارد شوید",
    errorRequiredEmailInput: "ایمیل را وارد کنید",
    errorRequiredPaaswordInput: "رمز عبور را وارد کنید",
    errorEmailInput: "ایمیل وارد شده نامعتبر است ",
    singUpBtn: "ثبت نام",
    passwordError: "رمز عبور باید حداقل 8 رقم باشد",
  },
};

export const dashboardLocalization = {
  header: {
    welcome: "خوش آمدید",
  },
  sidBar: {
    dashboar: "داشبورد",
    order: "سفارش ها",
    products: "کالاها",
    price: "قیمت و موجودی کالا",
    exit: "خروج از حساب کاربری",
  },
  loginPage: {
    emailPlaceholder: "tinankh@gmail.com",
    passwordPlaceholder: "12345678",
    emailLabel: "ایمیل:",
    passwordLabel: "رمزعبور:",
    buttonLabel: "ورود",
    welcome: "به بوکتین خوش آمدید",
    login: "به اکانت خود وارد شوید",
    errorRequiredEmailInput: "ایمیل را وارد کنید",
    errorEmailInput: "ایمیل وارد شده نامعتبر است ",
    errorRequiredPaaswordInput: "رمز عبور را وارد کنید",
    passwordError: "رمز عبور باید حداقل 8 رقم باشد",
  },
  proTabel: {
    image: "عکس محصول",
    name: "نام محصول",
    category: "دسته بندی",
    addPro: "اضافه کردن محصول",
    page: "صفحه",
    next: "بعدی",
    pre: "قبلی",
    actions: "عملیات",
  },
  invenTabel: {
    price: "قیمت",
    product: "نام کالا",
    inventory: "موجودی",
    save: "ذخیره",
    page: "صفحه",
    next: "بعدی",
    pre: "قبلی",
    acction: "عملیات",
    editProduct: "ویرایش موجودی محصول",
  },
  orderTabel: {
    userName: "نام کاربر",
    price: "مبلغ پرداختی",
    time: "زمان ثبت سفارش",
    latest: "قدیمی ترین",
    newest: "جدیدترین",
    placeholder: "انتخاب فیلتر",
  },
  orderModals: {
    cName: "نام مشتری :",
    adress: "آدرس :",
    phoneNumber: "شماره تماس :",
    OrderDAte: "تاریخ ثبت سفارش : ",
    product: "نام کتاب",
    count: "تعداد",
    payedPrice: "مبلغ پرداخت شده",
    deliveryBtn:"تحویل شد",
  },
  addModal: {
    photo: "عکس محصول",
    photoLabel: "عکس:",
    uploadBtn: "آپلود",
    namePlaceHolder: "طاعون",
    nameLabel: "نام محصول:",
    addBtn: "اضافه کردن",
    category1: "داستان کوتاه",
    category2: "ادبیات کلاسیک",
    category3: "فانتزی",
    category4: "ادبی",
    category5: "رمان",
    discriptionLabel: "توضیحات : ",
    adult: "بزرگسال",
    junior: "نوجوان",
    young: "جوان",
    selectCategory: "انتخاب دسته‌بندی",
    selectAge: "انتخاب گروه سنی",
  },
  deletModal: {
    text: "از حذف محصول اطمیان کامل دارید؟",
    canceled: "انصراف",
    accept: "تایید",
  },
  charts: {
    SaleChartTitle: "مقایسه فروش سال اتی و سال گذشته",
    SaleChartLabels: {
      farvardin: "فروردین",
      ordibehesht: "اردیبهشت",
      khordad: "خرداد",
      tir: "تیر",
      mordad: "مرداد",
      shahrivar: "شهریور",
      mehr: "مهر",
      aban: "آبان",
      azar: "آذر",
      Dy: "دی",
      Bahman: "بهمن",
      Esfand: "اسفند",
    },
    bestSellerChartTitle: "درصد فروش بر اساس دسته بندی",
    bestSellerChartLabels: {
      literary: "ادبی",
      fantasy: "فانتزی",
      novel: "رمان",
      poet: "ادبیات کلاسیک",
      others: "سایر",
    },
  },
};
export const singlePageLoc = {
  athur: "نویسنده : ",
  pages: "تعداد صفحه : ",
  cover: "جلد : ",
  name: "نام کتاب : ",
  category: "دسته بندی : ",
  price: "قیمت",
  order: "خرید",
  founder: "پدیدآورندگان",
  header: "بالای صفحه",
  buy: "خرید آنلاین",
};
export const checkoutPageLoc = {
  name: "نام :",
  LName: "نام خانوادگی :",
  phoneNumber: "شماره تلفن :",
  address: "آدرس پستی :",
  code: "کدپستی :",
  chekoutBtn: "ثبت سفارش",
  errorPhoneNumber: "تلفن همراه را وارد کنید",
  errorCode: "کدپستی را وارد کنید",
  errorPhoneNumberInput: "شماره تلفن وارد شده نامعتبر است ",
  errorCodeInput: "کدپستی وارد شده نامعتبر است ",
  errorName: "نام را وارد کنید",
  errorLName: "نام خانوادگی را وارد کنید",
  errorAddress: "آدرس را وارد کنید",
};
export const receipt = {
  disCount: "کد تخفیف : ",
  diCountBtn: "اعمال کد تخفیف",
  disCoutSuccess: "کد تخفیف اعمال شد✅",
  disCountUnSuccess: "کد تخفیف معتبر نیست!",
  bookPrice: "قیمت کتاب ها",
  totalDiscount: "تخفیف:",
  totalPrice: "قیمت نهایی",
  priceToPay: "مبلغ قابل پرداخت",
  payBtn: "اتمام خرید",
};
