export const pageLevelLocalization = {
  header: {
    home: "صفحه اصلی",
    fantasy: "فانتزی",
    history: "تاریخی",
    juniuor: "کودک و نوجوان",
    enigmatic: "معمایی",
    manga: "مانگا",
    play: "نمایشنامه",
    contact: "ارتباط با ما",
    about: "درباره ما",
  },
  footer: {
    address: "تهران - ستاری - بلوار لاله - پاساژ سمرقند طبقه 3 فروشگاه بوکتین",
    number: "021-4443258",
    text: "...بیشتر",
  },
};

export const dashboardLocalization = {
  header: {
    welcome: "خوش آمدید",
  },
  sidBar: {
    dashboar: "داشبورد",
    order: "سفارش ها",
    products: "کالاها",
    price: "قیمت و موجودی کالا",
    exit: "خروج از حساب کاربری",
  },
  loginPage: {
    emailPlaceholder: "tinankh@gmail.com",
    passwordPlaceholder: "12345678",
    emailLabel: "ایمیل:",
    passwordLabel: "رمزعبور:",
    buttonLabel: "ورود",
    welcome: "به بوکتین خوش آمدید",
    login: "به اکانت خود وارد شوید",
    errorRequiredEmailInput: "ایمیل را وارد کنید",
    errorEmailInput: "ایمیل وارد شده نامعتبر است ",
    errorRequiredPaaswordInput: "رمز عبور را وارد کنید",
    passwordError: "رمز عبور باید حداقل 8 رقم باشد",
  },
  proTabel: {
    image: "عکس محصول",
    name: "نام محصول",
    category: "دسته بندی",
    addPro: "اضافه کردن محصول",
    page: "صفحه",
    next: "بعدی",
    pre: "قبلی",
    actions: "عملیات",
  },
  invenTabel: {
    price: "قیمت",
    product: "کالا",
    inventory: "موجودی",
    save: "ذخیره",
    page: "صفحه",
    next: "بعدی",
    pre: "قبلی",
  },
  orderTabel: {
    userName: "نام کاربر",
    price: "مبلغ پرداختی",
    time: "زمان ثبت سفارش",
  },
  addModal: {
    photo: "عکس محصول",
    photoLabel: "عکس:",
    uploadBtn: "آپلود",
    namePlaceHolder: "طاعون",
    nameLabel: "نام محصول:",
    addBtn: "اضافه کردن",
    category1: "شعر",
    category2: "ادبیات کلاسیک",
    category3: "فانتزی",
    category4: "رمان های خارجی",
    category5: "داستان کوتاه",
    category6: "کودک و نوجوان",
  },
  deletModal: {
    text: "از حذف محصول اطمیان کامل دارید؟",
    canceled: "انصراف",
    accept: "تایید",
  },
  charts: {
    SaleChartTitle: "مقایسه فروش سال اتی و سال گذشته",
    SaleChartLabels: {
      farvardin: "فروردین",
      ordibehesht: "اردیبهشت",
      khordad: "خرداد",
      tir: "تیر",
      mordad: "مرداد",
      shahrivar: "شهریور",
      mehr: "مهر",
      aban: "آبان",
      azar: "آذر",
      Dy: "دی",
      Bahman: "بهمن",
      Esfand: "اسفند",
    },
    bestSellerChartTitle: "درصد فروش بر اساس دسته بندی",
    bestSellerChartLabels: {
      literary: "ادبی",
      fantasy: "فانتزی",
      novel: "رمان",
      poet: "ادبیات کلاسیک",
      others: "سایر",
    },
  },
};
